### ISSUE TITLE
Unprivileged installation script currently fails

### ISSUE THREAD

**Issue by jwimberl** [apptainer/apptainer-admindocs#134]
## Which Document page:

https://apptainer.org/docs/admin/main/installation.html#install-unprivileged-from-pre-built-binaries

### Expected results:

The install script will succesfully install apptainer, if the privileges and dependencies necessary are met.

### Actual results:

As of writing linux-mirrors.fnal.gov is reachable over HTTP but not HTTPS. This results in the installation script failing:

```
# curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s /opt/apptainer
Could not find apptainer version from https://linux-mirrors.fnal.gov/linux/fedora/epel/7/x86_64/Packages/a
```
This can be worked around currently by replacing https://linux-mirrors.fnal.gov with http://linux-mirrors.fnal.gov.

**Comment by DrDaveD** [comment]
Thanks for the suggestion, and I did notice that https://linux-mirrors.fnal.gov was having a problem yesterday, but it is working today.  It would be better if it had one or two alternative mirrors that it could use if one wasn't responding.  Using http is not a good alternative for installing software because of the lack of verification.
