### ISSUE TITLE
Import sylabs admindocs

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer-admindocs#146]
Import the following sylabs admindocs PRs:
- sylabs/singularity-admindocs#95
- sylabs/singularity-admindocs#120

Also review these to see if they're better than what we already have:
- sylabs/singularity-admindocs#116
- sylabs/singularity-admindocs#117
- sylabs/singularity-admindocs#136

**Comment by DrDaveD** [comment]
@afbjorklund Could you please look at sylabs/singularity-admindocs#116 to see if there's any of that you'd like to see imported into apptainer-admindocs?

**Comment by afbjorklund** [comment]
@DrDaveD : No, there doesn't seem to be anything in that singularity documentation that is not covered by apptainer.

It is possible to remove the Vagrant documentation, and to make the Lima documentation more verbose. But the vagrant is still valid, even if not Open Source and not supporting ARM, and I'm not sure about copying a lot of text from brew and lima because that probably means that it will need to be updated. The basics should stay more the same, over time...

----

Some differences:

1) Singularity (CE) is using Alma + EPEL, where Apptainer used the standard Ubuntu LTS. It was mostly due to the size. Singularity template is not bundled with Lima, so it is downloaded from `https:` instead of using `template:`

2) Singularity wrapper is done using shell flags (`-B`), instead of the more transparent `apptainer.lima` wrapper
It seems to have copied the bug with -H versus -B that apptainer had, which lead to having a read-only home...

Other issues are the same:

1) Where to store the images in the Lima instance, when home directory (`$PWD`) is read-only

2) Still using the default qemu and sshfs, instead of new vz and virtiofs (currently "experimental")
